### ISSUE TITLE
registros de 15/07

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/TDAH#3]
Quem tirou fotos suba aqui por favor:

**Comment by fczuardi** [comment]
- [Usando dados para melhorar a retenção e receita](https://github.com/calamar-io/TDAH/files/366541/tdah-2.pdf) by @vstabile 
- [Currying](https://github.com/fczuardi/tdahdeck01)

**Comment by fczuardi** [comment]
imagem do form: 

![tdah-s01e01-landscape](https://cloud.githubusercontent.com/assets/7760/16883158/fc1df0ca-4a98-11e6-8813-b7a0463f5517.jpg)

mesma ideia mas em portrait:

![tdah-s01e01](https://cloud.githubusercontent.com/assets/7760/16883179/0dc5eec2-4a99-11e6-8fa6-997e7bf3a349.jpg)

**Comment by thiagochristof** [comment]
![img_20160715_134254195](https://cloud.githubusercontent.com/assets/1921717/16884079/c9df65da-4a9d-11e6-947d-a8996c5d2c97.jpg)
![img_20160715_134258238](https://cloud.githubusercontent.com/assets/1921717/16884078/c9df8858-4a9d-11e6-83cf-3229ea891d22.jpg)
![img_20160715_134404360](https://cloud.githubusercontent.com/assets/1921717/16884080/c9e021c8-4a9d-11e6-91a4-85a98cb61dbf.jpg)
![img_20160715_134924098](https://cloud.githubusercontent.com/assets/1921717/16884081/c9e278d8-4a9d-11e6-98c5-5124d6fd29ba.jpg)
![img_20160715_134935766](https://cloud.githubusercontent.com/assets/1921717/16884082/c9e33688-4a9d-11e6-8482-9000e1577594.jpg)
![img_20160715_134953217](https://cloud.githubusercontent.com/assets/1921717/16884083/c9e6fe94-4a9d-11e6-8b91-6d0282b5757f.jpg)
![img_20160715_134957598](https://cloud.githubusercontent.com/assets/1921717/16884084/c9ff8f9a-4a9d-11e6-8b87-5360d1c4d436.jpg)
![img_20160715_140016871](https://cloud.githubusercontent.com/assets/1921717/16884085/c9fffdd6-4a9d-11e6-8334-fb5eda8d7338.jpg)
![img_20160715_140039843](https://cloud.githubusercontent.com/assets/1921717/16884086/ca03f530-4a9d-11e6-81d0-7f7fd4135be4.jpg)

**Comment by fczuardi** [comment]
valeu Thiago! publiquei o relatório com links e audio em https://github.com/calamar-io/TDAH/blob/master/S01E01.md
